### ISSUE TITLE
能移植到linux吗？

### ISSUE THREAD

**Issue by chenyanming** [dkw72n/xhcatv#1]
我想，如果能移植到linux，我手头上有块arm开发板，那么就不需要用电脑做服务器了。

**Comment by dkw72n** [comment]
linux不用这么麻烦...我是为了弄个gui出来才搞得这么复杂的....
我在路由器上就跑个python脚本发包拨号.

**Comment by chenyanming** [comment]
真的吗？我C++好差，研究你的代码好久都没搞懂，移植好久都不成功，因为我还在恶补socket的内容啊。。能共享下脚本不？

**Comment by dkw72n** [comment]
参考这个帖子27楼.http://forum.ubuntu.org.cn/viewtopic.php?f=121&t=100014&start=15

**Comment by chenyanming** [comment]
抓包我也不太懂。。看来要研究下才行啊

**Comment by dkw72n** [comment]
这个issue我关了, 有什么问题给我发邮件吧.
