### ISSUE TITLE
xhcatv在路由器上的实现

### ISSUE THREAD

**Issue by roubo** [dkw72n/xhcatv#2]
Hi, 请问是否有兴趣将该应用移植到路由器上，这样的话一个家庭里的设备都可以方便上网了。我是魔豆路由器 www.modouwifi.com 的工作人员。

**Comment by dkw72n** [comment]
路由器有啊~ 我自己就在用, 就一个python脚本就可以了.

**Comment by dkw72n** [comment]
脚本已上传, 需要请自取 https://gist.github.com/f43c6b3f08d36f524c5a.git

**Comment by roubo** [comment]
好的，感谢。
